name: Mayhem
true:
  pull_request: null
  push: null
  workflow_dispatch: null
env:
  IMAGE_NAME: ${{ github.repository }}
  REGISTRY: ghcr.io
jobs:
  build:
    name: Build mayhem fuzzing container
    outputs:
      image: ${{ steps.meta.outputs.tags }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Log in to the Container registry
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
    - id: meta
      name: Extract metadata (tags, labels) for Docker
      uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
    - name: Build and push Docker image
      uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      with:
        context: .
        file: mayhem/Dockerfile
        labels: ${{ steps.meta.outputs.labels }}
        push: true
        tags: ${{ steps.meta.outputs.tags }}
  mayhem:
    name: fuzz ${{ matrix.mayhemfile }}
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Start analysis for ${{ matrix.mayhemfile }}
      uses: ForAllSecure/mcode-action@v1
      with:
        args: --image ${{ needs.build.outputs.image }} --file ${{ matrix.mayhemfile
          }} --duration 300
        mayhem-token: ${{ secrets.MAYHEM_TOKEN }}
        sarif-output: sarif
    strategy:
      fail-fast: false
      matrix:
        mayhemfile:
        - mayhem/Mayhemfile
